/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Calendar.JCalendarFrame;
import Dao.FareConditionsDao;
import Dao.PriceDao;
import Model.FareConditions;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author bzach
 */
public class BuyTickets extends javax.swing.JFrame {
public int price = 0; 
    /**
     * Creates new form BuyTickets
     */
    public BuyTickets() {
        initComponents();
        this.Arr = null;
    }
     
    public BuyTickets(String Dep,String Arr) {
        initComponents();
        txtDep.setText(Dep);
        txtArr.setText(Arr);
        this.Arr = Arr;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private final String Arr;

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btnExit2 = new javax.swing.JButton();
        txtDep = new javax.swing.JLabel();
        txtArr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtClass = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        txtCost = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        lblPlace = new javax.swing.JLabel();
        txtPlaces = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        lblFlNum = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Buy Tickets");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 26, -1, -1));

        btnExit2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExit2.setText("Exit");
        btnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 26, 90, 30));

        txtDep.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtDep.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 150, 30));

        txtArr.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtArr.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 220, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("From");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 137, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("To");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Data");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 132, 40, 30));

        txtData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 132, 150, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Calendar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(732, 132, 100, 30));

        txtClass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 150, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText(" Check Price");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 120, 30));

        txtCost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCost.setText("Your ticket price will be:");
        getContentPane().add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 210, -1));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 30));

        lblPlace.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPlace.setText(" Places for this class:");
        getContentPane().add(lblPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        txtPlaces.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPlaces.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(txtPlaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 150, 30));

        btnBuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuy.setText("Buy");
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 120, 30));
        getContentPane().add(lblFlNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExit2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new JCalendarFrame(Arr);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<FareConditions> list = FareConditionsDao.getAllRecords();
        Iterator<FareConditions> itr = list.iterator();
        while (itr.hasNext()) {
            FareConditions fareConditionsObj = itr.next();
            txtClass.addItem(fareConditionsObj.getFareConditions());
        }

    }//GEN-LAST:event_formComponentShown

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
       String Arr = ((String) txtArr.getText());
       String Class = ((String) txtClass.getSelectedItem());
       price = Integer.parseInt(PriceDao.getPrice(Arr,Class));
       txtPrice.setText(PriceDao.getPrice(Arr, Class));
       txtPlaces.setText(PriceDao.getSeats(Class));
    }//GEN-LAST:event_jButton2MousePressed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:
        String Dep = ((String) txtDep.getText());
        String Arr = ((String) txtArr.getText());
        String Price = ((String) txtPrice.getText());
        String Cl = ((String) txtClass.getSelectedItem());
        String Data = ((String) txtData.getText());
        setVisible(false);
        new BuyTicket(Dep, Arr, Price, Cl,Data).setVisible(true);
    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFlNum;
    private javax.swing.JLabel lblPlace;
    private javax.swing.JLabel txtArr;
    private javax.swing.JComboBox<String> txtClass;
    private javax.swing.JLabel txtCost;
    public static javax.swing.JLabel txtData;
    private javax.swing.JLabel txtDep;
    private javax.swing.JLabel txtPlaces;
    private javax.swing.JLabel txtPrice;
    // End of variables declaration//GEN-END:variables
}
