/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Dao.BookingsSeatsDao;
import Dao.RegFlDao;
import Model.BookingsSeats;
import Model.RegFl;
import SeatAssigner.SeatAssigner;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author bzach
 */
public class BuyTicket extends javax.swing.JFrame {

    /**
     * Creates new form BuyTicket
     */
    public BuyTicket(String Dep, String Arr, String Price, String Cl, String Data) {
        initComponents();
        txtDep.setText(Dep);
        txtArr.setText(Arr);
        txtClass.setText(Cl);
        txtData.setText(Data);
        txtPrice.setText(Price);
        String seatClass = txtClass.getText();
        String seatNumber = SeatAssigner.assignSeat(seatClass);
        txtTest.setText(seatNumber);
        txtTest.hide();
    }

    public BuyTicket() {
        initComponents();

    }

    private void clear() {
        txtEmail.setText("");
        txtPersonal.setText("");
        txtPhoneNum.setText("");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDep = new javax.swing.JLabel();
        lblArr = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        LblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtDep = new javax.swing.JLabel();
        txtArr = new javax.swing.JLabel();
        txtClass = new javax.swing.JLabel();
        txtData = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        txtPersonal = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        btnPayment = new javax.swing.JButton();
        txtTest = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDep.setText(" Departure Airport");
        getContentPane().add(lblDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 82, 140, 30));

        lblArr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblArr.setText("Arrival Airport");
        getContentPane().add(lblArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 141, 140, 30));

        lblClass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClass.setText("Your Class");
        getContentPane().add(lblClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 198, 140, 30));

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblData.setText("Flight Date");
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 246, 140, 30));

        LblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LblName.setText("Personal data");
        getContentPane().add(LblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 294, 140, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEmail.setText("Email");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 342, 140, 30));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhone.setText("Phone Number");
        getContentPane().add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 390, 140, 30));

        lblPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrice.setText("Price");
        getContentPane().add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 438, 140, 30));

        txtDep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 82, 250, 30));

        txtArr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtArr, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 141, 250, 30));

        txtClass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 198, 250, 30));

        txtData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 246, 250, 30));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 438, 250, 30));

        txtPersonal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonalActionPerformed(evt);
            }
        });
        getContentPane().add(txtPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 294, 250, 30));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 342, 250, 30));

        txtPhoneNum.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumActionPerformed(evt);
            }
        });
        getContentPane().add(txtPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 390, 250, 30));

        btnPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPayment.setText(" Payment");
        btnPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMouseClicked(evt);
            }
        });
        getContentPane().add(btnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, 30));
        getContentPane().add(txtTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 48, 204, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonalActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_txtPersonalActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_txtPhoneNumActionPerformed

    private void btnPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMouseClicked

        RegFl regfl = new RegFl();
        txtDep.getText();
        Date date = null;
        try {
            date = new SimpleDateFormat("dd/MM/yyyy").parse(txtData.getText());
        } catch (ParseException ex) {
            Logger.getLogger(BuyTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
        String dateStr = new SimpleDateFormat("yyyy-MM-dd").format(date);
        regfl.setArr((String) txtArr.getText());
        regfl.setFareConditions(txtClass.getText());
        regfl.setFlightDate(dateStr);
        regfl.setName((String) txtPersonal.getText());
        regfl.setEmail((String) txtEmail.getText());
        regfl.setMobileNumber((String) txtPhoneNum.getText());
        regfl.setPrice((String) txtPrice.getText());
        regfl.setSeat(txtTest.getText());
        RegFlDao.save(regfl);
        BookingsSeats bookingsSeats = new BookingsSeats();
        bookingsSeats.setSeatNo(txtTest.getText());
        BookingsSeatsDao.UpDate(bookingsSeats);
        setVisible(false);
        new PaymentOption().setVisible(true);
    }//GEN-LAST:event_btnPaymentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblName;
    private javax.swing.JButton btnPayment;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblArr;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDep;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel txtArr;
    private javax.swing.JLabel txtClass;
    private javax.swing.JLabel txtData;
    private javax.swing.JLabel txtDep;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPersonal;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtTest;
    // End of variables declaration//GEN-END:variables
}
