/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Dao.AircraftCodeDao;
import Dao.BookingsSeatsDao;
import Dao.FareConditionsDao;
import Model.AircraftCode;
import Model.BookingsSeats;
import Model.FareConditions;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author bzach
 */
public class ManagerSeats extends javax.swing.JFrame {

    /**
     * Creates new form ManagerSeats
     */
    public ManagerSeats() {
        initComponents();
    }

    private void clear() {
        txtSeatNo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtSeatNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFareConditions = new javax.swing.JComboBox<>();
        txtAirCraftCode = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        btnStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Manager Seats");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, 30));

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Сlear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, 30));
        getContentPane().add(txtSeatNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 200, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("AirCraftCode");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 99, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("SeatNum");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 99, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("FareConditions");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 30));

        txtFareConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFareConditionsActionPerformed(evt);
            }
        });
        getContentPane().add(txtFareConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 200, 30));

        txtAirCraftCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAirCraftCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtAirCraftCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AirCraftCode", "SeatNum", "FareConditions"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 320, 390));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("*Click On Row to Delete Seats");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));

        btnStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.png"))); // NOI18N
        getContentPane().add(btnStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        BookingsSeats bookingsSeats = new BookingsSeats();
        bookingsSeats.setSeatNo(txtSeatNo.getText());
        bookingsSeats.setAirCraftCode((String) txtAirCraftCode.getSelectedItem());
        bookingsSeats.setFareConditions((String) txtFareConditions.getSelectedItem());
        BookingsSeatsDao.save(bookingsSeats);
        setVisible(false);
        new ManagerSeats().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtFareConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFareConditionsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFareConditionsActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<FareConditions> lis = FareConditionsDao.getAllRecords();
        Iterator<FareConditions> it = lis.iterator();
        while (it.hasNext()) {
            FareConditions fareConditionsObj = it.next();
            txtFareConditions.addItem(fareConditionsObj.getFareConditions());
        }
        ArrayList<AircraftCode> list = AircraftCodeDao.getAllRecords();
        Iterator<AircraftCode> itr = list.iterator();
        while (itr.hasNext()) {
            AircraftCode aircraftCodesObj = itr.next();
            txtAirCraftCode.addItem(aircraftCodesObj.getAircraftCode());
        }
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<BookingsSeats> list1 = BookingsSeatsDao.getAllRecords();
        Iterator<BookingsSeats> itr1 = list1.iterator();
        while (itr1.hasNext()) {
            BookingsSeats bookingsSeatsObj = itr1.next();
            dtm.addRow(new Object[]{bookingsSeatsObj.getAirCraftCode(), bookingsSeatsObj.getSeatNo(),bookingsSeatsObj.getFareConditions()});
        }
    }//GEN-LAST:event_formComponentShown

    private void txtAirCraftCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAirCraftCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAirCraftCodeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
                int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String AirCraftCode = model.getValueAt(index, 0).toString();
        String SeatNo = model.getValueAt(index, 1).toString();
        String FareConditions = model.getValueAt(index, 2).toString();
        int a = JOptionPane.showConfirmDialog(null, "Do you want to Delete " + SeatNo + " Airport", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            BookingsSeatsDao.delete(SeatNo);
            setVisible(false);
            new ManagerSeats().setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerSeats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerSeats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel btnStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> txtAirCraftCode;
    private javax.swing.JComboBox<String> txtFareConditions;
    private javax.swing.JTextField txtSeatNo;
    // End of variables declaration//GEN-END:variables

}
